### PR TITLE
21 progress module component

### LINKED ISSUE #21: Create ProgressModule Component
When we display the dashboard of a user we want to also display their progress for each module. So we will need to create a ProgressModule component to go within the dashboard component.

It's also a good idea to create some mock data to utilise within this component. Having the mock data set up in the same format as the wiki ensures that the real live data we send through later will be even more seamless to integrate.

_Think about whether this is likely to be functional or class based._  _Also think if how this component will be used, will we want to map data into this component?_

You may also need to ensure that this component has a client-side route set up too. 

Tasks:
- [x] Check the [wiki](https://github.com/kahikatea-2019/MOA/wiki) for relevant information.
- [x] Create component file. 
- [x] Create mock data which is in the same shape as the wiki and used within the component.
- [x] Display header component within the dashboard. 
- [x] Create client-side route for component. 
- [x] Write tests for this component.

You won't need to do any design just yet, just the basics to get this showing.

### PR DESCRIPTION
**Pull request by MurdocAV**
Wanting some input on what needs to be changed in this component.

Closes #21

### CODE REVIEW

**Comment by chrislaupama** [comment]
@MurdocAV can you please merge this ticket with the current version of dev

**Review by chrislaupama — CHANGES_REQUESTED** [review]
@MurdocAV can you please merge this ticket with the current version of dev

**Comment by MurdocAV** [comment]
Thanks Chris, Updated to the latest dev branch

**Review by chrislaupama — APPROVED** [review]
Daaaaamn good work Azaan!

**Pull request merged**
